model: models.EXIF_SC
model_args:
  weight_file: artifacts/exif_sc.npy
  device: cuda:0

dataset: datasets.InTheWildDataset
dataset_args:

save: True
# resize: [1152, 768]  # For Columbia
# resize: [600, 700]  # For Hays
resize: [1000, 1400]  # For In-The-Wild